### ISSUE TITLE
Asynchronous support

### ISSUE THREAD

**Issue by hhelwich** [juancabrera/gulp-traceur-cmdline#12]
There seems to be a bug in this plugin (v1.1.4) with asynchronous support.
If i have a task which depends on the traceur output, it does not work as traceur is not done after notifying finish. Here is some example code that does not work as expected:
```javascript
var gulp = require("gulp");
var traceur = require("gulp-traceur-cmdline");
var uglify = require("gulp-uglify");

gulp.task("traceur", function() {
  gulp.src("src/foo.js").pipe(traceur({
    modules : "inline",
    out     : "build/foo.js",
    debug   : false
  }));
});

gulp.task("uglify", ["traceur"], function() {
  gulp.src("build/foo.js").pipe(uglify()).pipe(gulp.dest("build/bar"));
});
```
If i give the traceur task some time, it works:
```javascript
gulp.task("traceur", function(done) {
  gulp.src("src/foo.js").pipe(traceur({
    modules : "inline",
    out     : "build/foo.js",
    debug   : false
  }));
  setTimeout(done, 1000);
});
```

**Comment by juancabrera** [comment]
Yeah, this is a known issue (#7). Going to try to make time next week to fix it, PR are welcomes too!

**Comment by juancabrera** [comment]
fixed on latest version, please check it out and let me know how it works!

**Comment by hhelwich** [comment]
It is working now. Thank you!
