### ISSUE TITLE
errs is not defined

### ISSUE THREAD

**Issue by simax** [juancabrera/gulp-traceur-cmdline#13]
I carried out the following steps 
1. ```npm install traceur --save-dev```
2. ```npm install gulp-traceur-cmdline --save-dev```

If I run ```traceur --modules inline --out dest/scripts/mainTranspiled.js src/scripts/script1.js``` Then ```mainTranspiled.js``` is produced correctly 

If I create a gruntfile.js
```
var gulp = require('gulp'),
    rename = require('gulp-rename'),
    concat = require('gulp-concat'),
    uglify = require('gulp-uglify'),
    gulpTraceurCmdline = require('gulp-traceur-cmdline');

// The following task isn't used
gulp.task('process-scripts-example', function () {
  return gulp.src('src/scripts/*.js')
          .pipe(concat('main.js'))
          .pipe(uglify())
          .pipe(rename({suffix:'.min'}))
          .pipe(gulp.dest('dest/scripts'));
});

gulp.task('gulpTraceurCmdline',function() {
  gulp.src("./src/scripts/*.js")
    .pipe(gulpTraceurCmdline({
      modules : 'inline'
    }))
    .pipe(gulp.dest('./dest/scripts/'));
});

gulp.task('default', ['gulpTraceurCmdline']);
```

and then issue ```gulp``` I get the following:
```
ReferenceError: errs is not defined
    at C:\Development\Blah\src\Blah\node_modules\gulp-traceur-cmdline\index.js:38:75
    at ChildProcess.exithandler (child_process.js:751:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
```

Any idea what's wrong?

**Comment by juancabrera** [comment]
@simax I think its because you are trying to transpile more than one file (```gulp.src("./src/scripts/*.js")```). I built this mostly because I wanted to use one of the best features of traceur: inline modules.

I'd recommend to have a single file ```main.js``` or ```app.js``` and in that file import all the files you need, for example:

main.js
```
import module1 from './module1.js';
import module2 from './module2.js';
import module3 from './module3.js';
```

module1.js
class gDom {
  constructor(selector) {
    if (typeof(selector) == "object") {
      this.elements = [selector];
    } else {
      this.elements = document.querySelectorAll(selector);
    }
  }

  addClass(cl) {
    Array.prototype.forEach.call(this.elements, function(el) {
      el.classList.add(cl);
    });
    return true;
  }

**Comment by juancabrera** [comment]
Fixed the error handler.
