### ISSUE TITLE
Error: The system cannot find the file specified

### ISSUE THREAD

**Issue by Shershnev-AV** [juancabrera/gulp-traceur-cmdline#15]
I run two tasks with `gulpTraceurCmdline` in parallel, so I think problem is "tempout.js" file
https://github.com/juancabrera/gulp-traceur-cmdline/blob/master/lib/traceur_command_builder.js#L18

**Comment by juancabrera** [comment]
Just published a new version of it (1.3.7) with this fixed !

**Comment by Shershnev-AV** [comment]
Works fine now
thank you!

minor fix: move "btoa" from "devDependencies" to "dependencies"
