### ISSUE TITLE
change signature of gulpTraceurCmdline

### ISSUE THREAD

**Issue by david-gang** [juancabrera/gulp-traceur-cmdline#6]
I have the following comments regarding the signature of the gulpTraceurCmdline command.

The current signature is 

```javascript
gulpTraceurCmdline('/usr/local/bin/traceur', {
      modules : 'inline',
      out     : './dist/styleguide/js/main.js',
      debug   : false
    })
```

I have the following comments:

Why do we need to specify the command line?

We could just add traceur as a dependency in the package.json and we could then call it locally through the node_modules folder.

I also think that it would be nicer to differentiate between the command line arguments and our node arguments, so that all the arguments the user wants to pass to the traceur command line we will just pass through. This would make us life easier to maintain the code. We would not have to add every option alone and duplicate code.

```javascript
gulpTraceurCmdline({
      modules : 'inline',
      out     : './dist/styleguide/js/main.js',
      
    },
{
clear: true,
debug   : false,
traceurcmd: '/usr/local/bin/traceur'
}
)
```

The only minus is that it breaks backward compatibility, but it will make life much easier in the future.

**Comment by mickeyvip** [comment]
Hi.

Good change, but I am having problem running the plugin:

```bash
[20:03:42] Using gulpfile ~/dev/nodejs/ToDoListES6/gulpfile.js
[20:03:42] Starting 'default'...
[20:03:42] Finished 'default' after 4.74 ms
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Command failed: /bin/sh -c ./node_modules/gulp-traceur-cmdline/node_modules/traceur/traceur --modules=inline --out=./out/todolist.module.js  /Users/mickey/dev/nodejs/ToDoListES6/src/todolist.module.js
/bin/sh: ./node_modules/gulp-traceur-cmdline/node_modules/traceur/traceur: No such file or directory

    at ChildProcess.exithandler (child_process.js:732:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1000:16)
    at Socket.<anonymous> (child_process.js:1168:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:461:12)
```

seems like the path to the `traceur` is incorrect (or dependent on `gulpfile.js` location?)

I have changed the path from: 
```javascript
traceurcmd: "./node_modules/gulp-traceur-cmdline/node_modules/traceur/traceur"
```
to:
```javascript
traceurcmd: __dirname + "/node_modules/traceur/traceur"
```
and it fixed it.
