### ISSUE TITLE
make out file stream to the next pipe

### ISSUE THREAD

**Issue by david-gang** [juancabrera/gulp-traceur-cmdline#7]
As mentioned in #3 i tried to make the following

```javascript
var gulp = require('gulp');
var gulpTraceurCmdline = require('gulp-traceur-cmdline');
var uglify = require('gulp-uglify');
var debug = require('gulp-debug');

gulp.task('default',function() {
    gulp.src("./src/b.js")
        .pipe(gulpTraceurCmdline('traceur', {
            modules : 'register',
            out     : './dist/all.js',
            debug   : true,
            'source-maps': 'file'
        }))
        .pipe(debug({verbose: true}))
        .pipe(uglify())
        .pipe(gulp.dest('dist'));

});
```
This does not work.
The reason is that we don't stream the results further to the next pipe. What do you think?
Should we maybe stream the file out result content to the next pipe if the user specified the out argument? This would make the module more convenient.

**Comment by juancabrera** [comment]
@david-gang finally how did you figure out this ? you fixed it ?

**Comment by david-gang** [comment]
@juancabrera I did not look at it.
I think that it wouldn't be a problem to solve this.
We have just to think about the different output options of the traceur command line.
Could it be a single file, output directory, multiple files?
Once they are compiled we can give a solution here.

**Comment by juancabrera** [comment]
fixed on latest version, please check it out and let me know how it works!
